WEB/Controllers/InterviewController.cs
using Domain.Entities;
using PI.Service;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB.Controllers
{
    public class InterviewController : Controller
    {
        InterviewService Is;
        CandidatService Ps;
        ProjectManagerService CS;
        EmailService Ms;
        public InterviewController()
        {
            Is = new InterviewService();
            Ps = new CandidatService();
            CS = new ProjectManagerService();
            Ms = new EmailService();

        }
        // GET: Interview
        public ActionResult Index()
        {
            return View(Is.GetMany());
        }

        // GET: Interview/Details/5
        public ActionResult Details(int id)
        {
            return View(Is.GetById(id));
        }
        [HttpPost]
        public ActionResult Index(string filtre)
        {
            var list = Is.GetMany();


            // recherche
            if (!String.IsNullOrEmpty(filtre))
            {
                list = list.Where(m => m.Interview_Room.ToString().Contains(filtre)).ToList();
            }

            return View(list);



        }

        // GET: Interview/Create
        public ActionResult Create()
        {
            var candidats = Ps.GetMany();
            ViewBag.Candidat_Id = new SelectList(candidats, "Candidat_Id", "Candidat_FullName");

            var projectmanagers = CS.GetMany();
            ViewBag.ProjectManager_Id = new SelectList(projectmanagers, "ProjectManager_Id", "ProjectManager_FullName");

            return View();
        }

        // POST: Interview/Create
        [HttpPost]
        public ActionResult Create(Interview p)
        {
            Is.Add(p);
            Is.Commit();
            Candidat C = Ps.GetById(p.Candidat_Id);

            EmailService Ms = new EmailService();
            Ms.receiver_Email = C.Candidat_Email;
     
            Ms.receiver_FullName = C.Candidat_FullName;
            Ms.Mail_Subject = "Availablity";
            Ms.Mail_Body = "you have to check your interview's date";
            Ms.SendEmail();
            


            return RedirectToAction("index");
            
        }

        // GET: Interview/Edit/5
        public ActionResult Edit(int id)
        {
            Interview v = Is.GetById(id);
            if (v == null)
            {
                return HttpNotFound();
            }
            return View(Is.GetById(id));
        }

        // POST: Interview/Edit/5
        [HttpPost]
        public ActionResult Edit(Interview p)
        {
            Interview p1 = Is.GetById(p.Interview_Id);
            p1.Interview_Date = p.Interview_Date;
            p1.Interview_Object = p.Interview_Object;
            p1.Interview_Description = p.Interview_Description;
            p1.Interview_Room = p.Interview_Room;
            p1.Candidat_Availibility = p.Candidat_Availibility;
            p1.ProjectManager_Availibility = p.ProjectManager_Availibility;
            if (ModelState.IsValid)
            {
                Is.Update(p1);
                Is.Commit();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // GET: Interview/Delete/5
        public ActionResult Delete(int id)
        {
            return View(Is.GetById(id));
        }

        // POST: Interview/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Interview p)
        {
            p = Is.GetById(id);
            Is.Delete(p);
            Is.Commit();
            return RedirectToAction("Index");
        }
    }
}

WEB/Views/Interview/Create.cshtml
@model Domain.Entities.Interview
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Interview", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Interview</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Interview_Date, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.Interview_Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Object, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Interview_Object, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Interview_Object, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Interview_Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Interview_Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Room, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Interview_Room, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Interview_Room, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Candidat.Candidat_FullName, htmlAttributes: new { @class = "control-label col-md-2" })
        @*@Html.LabelFor(model => model.Candidat_Id, "Candidat_Id", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.Candidat_Id, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.DropDownList("Candidat_Id", (SelectList)ViewData["Candidats"])
            @* @Html.ValidationMessageFor(model => model.Candidat_Id, "", new { @class = "text-danger" })*@
            @Html.ValidationMessageFor(model => model.Candidat)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Candidat_Availibility, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Candidat_Availibility, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Candidat_Availibility, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProjectManager_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        @*@Html.LabelFor(model => model.Offre, "Offre_Name", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.DropDownList("ProjectManager_Id", (SelectList)ViewData["ProjectManagers"])
            @*@Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })*@
            @Html.ValidationMessageFor(model => model.ProjectManager)

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProjectManager_Availibility, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectManager_Availibility, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectManager_Availibility, "", new { @class = "text-danger" })
        </div>
    </div>





    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WEB/Views/Interview/Delete.cshtml
@model Domain.Entities.Interview
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3><strong>Are you sure you want to delete this?</strong></h3>
<div>
    <h4>Interview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            model.Interview_Date
        </dt>

        <dd>
             model.Interview_Date
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Interview_Object)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interview_Object)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Interview_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interview_Description)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Candidat_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidat_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidat_Availibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidat_Availibility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectManager_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectManager_Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjectManager_Availibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectManager_Availibility)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WEB/Views/Interview/Details.cshtml
@model Domain.Entities.Interview
@{
    ViewBag.Title = "Details";
}
<h2>Details</h2>
<div>
    <h4>Interview</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.Interview_Object)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interview_Object)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Interview_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interview_Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Interview_Room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interview_Room)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Candidat_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidat_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidat_Availibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidat_Availibility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectManager_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectManager_Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjectManager_Availibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectManager_Availibility)
        </dd>


    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Edit", "Edit", new { id = Model.Interview_Id }) |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WEB/Views/Interview/Edit.cshtml
@model Domain.Entities.Interview
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Interview</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Interview_Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Interview_Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Object, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Interview_Object, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Interview_Object, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Interview_Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Interview_Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Interview_Room, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Interview_Room, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Interview_Room, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Interview_Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Candidat_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Candidat_Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Candidat_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Candidat_Availibility, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Candidat_Availibility, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Candidat_Availibility, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProjectManager_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectManager_Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectManager_Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProjectManager_Availibility, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectManager_Availibility, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectManager_Availibility, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>