WEB/Controllers/ValidationController.cs
using Domain.Entities;
using PI.Service;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB.Controllers
{
    public class ValidationController : Controller
    {
        ValidationService Ps;
        CandidatService CS;
        OffreService OS;
        public ValidationController()
        {
            Ps = new ValidationService();
            CS = new CandidatService();
            OS = new OffreService();
        }
        [Authorize]
        public ActionResult Index()
        {
            return View(Ps.GetMany());
        }
        // GET: Validation/Details/5
        public ActionResult Details(int id)
        {
            return View(Ps.GetById(id));
        }
        /*[HttpPost]
        public ActionResult Index(string filtre)
        {
            var list = Ps.GetMany();


            // recherche
            if (!String.IsNullOrEmpty(filtre))
            {
                list = list.Where(m => m.Validateur_Name.ToString().Contains(filtre)).ToList();
            }

            return View(list);



        }*/

        // GET: Validation/Create
        public ActionResult Create()
        { 
            //test git
            var candidats = CS.GetMany();
            ViewBag.Candidat_Id = new SelectList(candidats, "Candidat_Id", "Candidat_FullName");

            var offres = OS.GetMany();
            ViewBag.Offre_Id = new SelectList(offres, "Offre_Id", "Offre_Name");

            return View();
        }

        // POST: Validation/Create
        [HttpPost]
        public ActionResult Create(Validation p)
        {
            Ps.Add(p);
            Ps.Commit();
            return RedirectToAction("index");
        }

        // GET: Validation/Edit/5
        public ActionResult Edit(int id)
        {
            Validation v = Ps.GetById(id);
            if (v == null)
            {
                return HttpNotFound();
            }
            return View(v);
        }

        // POST: Validation/Edit/5
        [HttpPost]
        public ActionResult Edit( Validation p)
        {
            Validation p1 = Ps.GetById(p.Validation_Id);
            p1.Validation_State = p.Validation_State;
        
            p1.Validation_desc = p.Validation_desc;
            if (ModelState.IsValid) { 
            Ps.Update(p1);
            Ps.Commit();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: Validation/Delete/5
        public ActionResult Delete(int id)
        {
            return View(Ps.GetById(id));
        }

        // POST: Validation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Validation p)
        {
            p = Ps.GetById(id);
            Ps.Delete(p);
            Ps.Commit();
            return RedirectToAction("Index");
        }
    }
}

WEB/Views/Validation/Create.cshtml
@model Domain.Entities.Validation

@{
    ViewBag.Title = "Create";

}
@*hello*@
<h2>Create</h2>
@using (Html.BeginForm("Create", "Validation", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Validation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Validation_State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Validation_State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Validation_State, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Validation_desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Validation_desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Validation_desc, "", new { @class = "text-danger" })
            </div>
        </div>






        @*<div class="form-group">
                @Html.LabelFor(model => model.ImageUrl2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageUrl2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageUrl2, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @*@<div class="editor-label">
                @Html.LabelFor(model => model.ImageUrl2)
            </div>
            <div class="editor-field">
                Upload a file
                @Html.TextBox("file", "", new { type = "file" })

                @Html.ValidationMessageFor(model => model.ImageUrl2)
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Candidat.Candidat_FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.Candidat_Id, "Candidat_Id", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Candidat_Id, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("Candidat_Id", (SelectList)ViewData["Candidats"])
                @* @Html.ValidationMessageFor(model => model.Candidat_Id, "", new { @class = "text-danger" })*@
                @Html.ValidationMessageFor(model => model.Candidat)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Offre.Offre_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.Offre, "Offre_Name", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("Offre_Id", (SelectList)ViewData["Offres"])
                @*@Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })*@
                @Html.ValidationMessageFor(model => model.Offre)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WEB/Views/Validation/Delete.cshtml
@model Domain.Entities.Validation
@{
                /**/

                ViewBag.Title = "Delete";
}
@*hello2*@
@*hello3*@

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Validation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Validation_State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Validation_State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Validateur_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Validateur_Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Validation_desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Validation_desc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidat_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidat_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offre_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offre_Id)
        </dd>







    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WEB/Views/Validation/Details.cshtml
@model  Domain.Entities.Validation
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<table class="table">


    <tr>
        <td>
            <div class="user-specs">
                <h3> @Html.DisplayFor(modelItem => Model.Validation_State) </h3>
                <span>Request Response</span>
            </div>
        </td>
        <td>
            <ul class="user-fw-status">
                <li>
                    <h4>About You</h4>
                    <span>

                        @Html.DisplayFor(modelItem => Model.Validation_desc)

                    </span>
                </li>
            </ul>
        </td>
        <td>
            <ul class="user-fw-status">
                <li>
                    <h4>Offer's Name</h4>
                    <span>

                        @Html.DisplayFor(modelItem => Model.Offre.Offre_Name)

                    </span>
                </li>
            </ul>
        </td>




        @*<td>
            @Html.DisplayFor(modelItem => item.ImageUrl2)
        </td>*@
        @*@<td>
            @{string path = "~/Content/Upload/" + @item.ImageUrl2;}

            <img src="@Url.Content(path)" width="50" height="50" />
        </td>*@

        @Html.ActionLink("Back to List", "Index")
    </tr>
     
</table>

WEB/Views/Validation/Edit.cshtml
@model Domain.Entities.Validation
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Validation</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   
    





    @Html.HiddenFor(model => model.Validation_Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Validation_State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Validation_State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Validation_State, "", new { @class = "text-danger" })
        </div>
    </div>

    
    <div class="form-group">
        @Html.LabelFor(model => model.Validation_desc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Validation_desc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Validation_desc, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>